#!/bin/sh

### BEGIN INIT INFO
# Provides:          pathfinder-service
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Pathfinder Service
# Description:       Service for the Pathfinder application
### END INIT INFO

# Add your custom script commands here

case "$1" in
    start)
        # Start command
        /usr/bin/pathfinder
        ;;
    stop)
        # Stop command
        # Add any necessary stop commands here
        ;;
    restart)
        # Restart command
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0